name: Milvus2 Node sdk check when open pr

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize]
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Read package.json
        uses: jaywcjlove/github-action-package@main
        id: info

      - name: Show target Milvus version
        run: echo "Milvus Version is ${{ steps.info.outputs.milvusVersion }}"

      - name: Run target Milvus
        run: |
          wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
          sed -i -e "s/milvusdb.*$/milvusdb\/milvus:${{ steps.info.outputs.milvusVersion }}/g" docker-compose.yml
          docker-compose up -d

      - name: update submodules
        run: |
          git submodule init
          yarn pre

      - name: Run Test coverage
        run: |
          yarn
          yarn build-test
          yarn coverage
