name: Run tests and coverage

on:
  pull_request:
    branches:
      - main
      - 2.4
    types: [opened, synchronize]
    paths-ignore:
      - '.github/**'
      - '*.md'
  push:
    branches:
      - main
      - 2.4
    paths-ignore:
      - '.github/**'
      - '*.md'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Read package.json
        uses: jaywcjlove/github-action-package@main
        id: info

      - name: Show target Milvus version
        run: echo "Milvus Version is ${{ steps.info.outputs.milvusVersion }}"

      - name: Run target Milvus
        run: |
          wget https://raw.githubusercontent.com/milvus-io/milvus/master/deployments/docker/standalone/docker-compose.yml -O docker-compose.yml
          sed -i -e "s/milvusdb.*$/milvusdb\/milvus:${{ steps.info.outputs.milvusVersion }}/g" docker-compose.yml
          docker compose up -d

      - name: update submodules
        run: |
          git submodule init
          yarn pre

      - name: Run Test coverage
        run: |
          yarn
          yarn build-test
          yarn coverage

      - name: send to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
